### ISSUE TITLE
Inferencing on jetson

### ISSUE THREAD

**Issue by saquibntt** [bricewalker/Hey-Jetson#1]
I am interested in this project for doing emotion detection from speech. 

Do we need to use flask for inferencing on jetson. I mean there are projects which do inferencing by direct deployment of model like here  https://github.com/dusty-nv/jetson-inference

Any advice for emotion detection from speech for this project

Thanks

**Comment by bricewalker** [comment]
Hi, you definitely don't need to use flask. I built the web app to allow people to interact with the model and see what kind of performance and speed the Jetson board is capable of. The jupyter notebook I provided allows you to run inference on device outside of the flask web app. The Jetson uses Linux4Tegra, so you should be able to run models for inference just as you would on your desktop. The only caveat being the fact that many libraries (like Librosa for example) won't work on ARM based chipsets.
