### ISSUE TITLE
Getting an error while building environment

### ISSUE THREAD

**Issue by wulfric47** [bricewalker/Hey-Jetson#5]
Getting this error:

conda env create -f environment.yml
Solving environment: failed

ResolvePackageNotFound: 
  - openssl==1.1.1b=hfa6e2cd_2
  - m2w64-flac==1.3.1=3
  - icu==58.2=ha66f8fd_1
  - h5py==2.9.0=py37h5e291fa_0
  - python==3.7.3=h8c8aaf0_1
  - qt==5.9.7=vc14h73c81de_0
  - mkl-service==2.0.2=py37he774522_0
  - cryptography==2.7=py37hb32ad35_0
  - pyyaml==5.1=py37he774522_0
  - winpty==0.4.3=4
  - tensorflow-base==1.13.1=gpu_py37h871c8ca_0
  - matplotlib==3.1.0=py37hc8f65d3_0
  - wincertstore==0.2=py37_0
  - mkl_fft==1.0.12=py37h14836fe_0
  - grpcio==1.16.1=py37h351948d_1
  - msys2-conda-epoch==20160418=1
  - m2w64-speex==1.2rc2=3
  - tensorboard==1.13.1=py37h33f27b4_0
  - yaml==0.1.7=hc54c509_2
  - protobuf==3.8.0=py37h33f27b4_0
  - mkl_random==1.0.2=py37h343c172_0
  - m2w64-libogg==1.3.2=3
  - m2w64-gcc-libs==5.3.0=7
  - m2w64-gcc-libgfortran==5.3.0=6
  - m2w64-libsndfile==1.0.26=2
  - libprotobuf==3.8.0=h7bd577a_0
  - zlib==1.2.11=h62dcd97_3
  - hdf5==1.10.4=h7ebc959_0
  - pyqt==5.9.2=py37h6538335_2
  - libsodium==1.0.16=h9d3ae62_0
  - sip==4.19.8=py37h6538335_0
  - pyrsistent==0.14.11=py37he774522_0
  - m2w64-gcc-libs-core==5.3.0=7
  - mistune==0.8.4=py37he774522_0
  - sqlite==3.28.0=he774522_0
  - m2w64-speexdsp==1.2rc3=3
  - pyzmq==18.0.0=py37ha925a31_0
  - pywinpty==0.5.5=py37_1000
  - libpng==1.6.37=h2a8f88b_0
  - m2w64-gmp==6.1.0=2
  - icc_rt==2019.0.0=h0cc432a_1
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - pandas==0.24.2=py37ha925a31_0
  - pycrypto==2.6.1=py37hfa6e2cd_1002
  - jpeg==9b=hb83a4c4_2
  - mkl==2019.4=245
  - m2w64-libvorbis==1.3.5=2
  - tornado==6.0.2=py37he774522_0
  - intel-openmp==2019.4=245
  - cffi==1.12.3=py37h7a1dbc1_0
  - statsmodels==0.9.0=py37h452e1ab_0
  - numpy==1.16.4=py37h19fb1c0_0
  - pyreadline==2.1=py37_1
  - freetype==2.9.1=ha9979f8_1
  - vs2015_runtime==14.15.26706=h3a45250_4
  - win_inet_pton==1.1.0=py37_0
  - scikit-learn==0.21.2=py37h6288b17_0
  - kiwisolver==1.1.0=py37ha925a31_0
  - vc==14.1=h0510ff6_4
  - markupsafe==1.1.1=py37he774522_0
  - tensorflow==1.13.1=gpu_py37h83e5d6a_0
  - zeromq==4.3.1=h33f27b4_3
  - numpy-base==1.16.4=py37hc3f5095_0
  - scipy==1.2.1=py37h29ff71c_0

**Comment by bricewalker** [comment]
Hi, I just uploaded a fixed conda env file. Can you try again with the updated version?

**Comment by shriramhr** [comment]
Thanks a lot. It was me who posted this initially, a colleagues ID was logged into the system when I posted it. I got it to run without conda, using docker and the requirements txt which I had to tweak a bit to update certain libraries. I hope that method is fine too because it starts training.
