### ISSUE TITLE
run_inference() not working properly

### ISSUE THREAD

**Issue by michaelguo32** [bricewalker/Hey-Jetson#50]
So I am trying to translate an audio file from the LibriSpeech data set using the run_inference() function in the make_predictions.py file by loading up model_11.h5, but the predicted translation is only 2 letters long. This is true for the other audio samples I have tried as well where I only get an output text of 2 letters. 
The output array generated by the model's predict() method, which is saved under the variable "prediction", for one of the audio samples I've tried is in the shape of (1, 149, 29), but the tensor generated by the ctc_decode() method is in the shape of (1, 2). So I'm guessing that something is wrong with the decoder? I can't quite figure it out.

Is this an issue that you have encountered before? I've attached the python script I've used to run the inference along with the sample audio file and the output to the screen.

[file.zip](https://github.com/bricewalker/Hey-Jetson/files/3645390/file.zip)

**Comment by bricewalker** [comment]
Hi, how did you train this model? I don't see a train_model function in your inference script. There is one in the provided make_predictions.py script. If you are using the model file I trained, you can see in the notebook that I did not allow the model to complete training so it is likely not going to perform well.

**Comment by michaelguo32** [comment]
I was using the model that you trained. I thought that you've finished training the model_11 and some of the earlier models since you were able to get fairly good predictions in the Jupyter notebook. In any case, shouldn't your models(even with unfinished training) give better predictions than the 2 letter outputs that I'm getting?

**Comment by bricewalker** [comment]
Speech recognition is very difficult. Most of these models do not perform very well.
