### ISSUE TITLE
Portuguese data corpus;

### ISSUE THREAD

**Issue by IsmaelEzequiel** [bricewalker/Hey-Jetson#53]
I'm trying to running this model usign a portuguese data corpus, but, I don't know how exactly use a PT-BR dataset because of the accents that have in portuguese, like:

**ACCENTS = 'ãõçâêôáíóúàüóé'**

how can I add these characters to this model?

ty

**Comment by bricewalker** [comment]
Hi, you will need to update the character mappings in these lines. Just add the characters and map them to additional numbers.

# Mapping each character that could be spoken at each time step

char_map_str = """
' 0
<SPACE> 1
a 2
b 3
c 4
d 5
e 6
f 7
g 8
h 9
i 10
j 11
k 12
l 13
m 14
n 15
o 16
p 17
q 18
r 19
s 20
t 21
u 22
v 23
w 24
x 25
y 26
z 27
"""
# This leaves "blank" character mapped to number 28

char_map = {}
index_map = {}
for line in char_map_str.strip().split('\n'):
    ch, index = line.split()
    char_map[ch] = int(index)
    index_map[int(index)+1] = ch
index_map[2] = ' '
