### ISSUE TITLE
jetson_requirement.txt too many missing packages

### ISSUE THREAD

**Issue by ashokbabus** [bricewalker/Hey-Jetson#56]
I have Jetson nano, with L4T 4.2.
The pip install -r jetson_requirement.txt doesn't run to completion. 

First package which is not found is apturl.

**Comment by bricewalker** [comment]
I mentioned in the readme that many packages on the Jetson will need to be installed with apt-get: 'Note: You may need to install some libraries using apt-get with a command like this: sudo apt-get install python3-<libraryname>'

This was built for the TX2. I don't own a nano and won't be purchasing one so hopefully someone can update this.
